@baseurl = http://localhost:3000

### get index
GET {{baseurl}}

### post signup
POST {{baseurl}}/signup
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

### post login
POST {{baseurl}}/login
Authorization: Basic a a
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

### like post
PUT {{baseurl}}/post/1/like
Content-Type: application/json

{
  "userid": 1
}

### like post 2
PUT {{baseurl}}/post/2/like
Content-Type: application/json

{
  "userid": 1
}
