@baseurl = http://localhost:3000

### get index
GET {{baseurl}}

### post signup
POST {{baseurl}}/signup
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

### post login
POST {{baseurl}}/auth/login
# Authorization: Basic a a
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

### like post
PUT {{baseurl}}/post/1/like
Content-Type: application/json

{
  "userid": 1
}

### like post 2
PUT {{baseurl}}/post/2/like
Content-Type: application/json

{
  "userid": 1
}

### get user
GET {{baseurl}}/user/3

### delete user
DELETE {{baseurl}}/user/2

### update user
PUT {{baseurl}}/user/2/profile
Content-Type: application/json

{
  "displayName": "iamb",
  "bio": "my name is b",
  "private": true
}

### update user password
PUT {{baseurl}}/user/1/profile/password
Content-Type: application/json

{
  "password": "b"
}

### follower request
POST {{baseurl}}/user/1/follow
Content-Type: application/json

{
  "userid": 2
}

### unfollow
DELETE  {{baseurl}}/user/3/follow
Content-Type: application/json

{
  "userid": 3
}

### get follower
GET {{baseurl}}/user/3/follower

### get posts
GET {{baseurl}}/post HTTP/1.1

### get posts page2
GET {{baseurl}}/post?page=2 HTTP/1.1

### get user posts
GET {{baseurl}}/user/1/post HTTP/1.1

### get reposted users
GET {{baseurl}}/post/407/repost/user HTTP/1.1

### get user chats
GET {{baseurl}}/chat/user/1 HTTP/1.1
